### ISSUE TITLE
BlackJack Assignment

### ISSUE THREAD

**Issue by rvaswani** [rvaswani/ICS3U#2]
Please mark my assignment. You are the best teacher ever.

**Comment by kevindeslauriers** [comment]
Excellent Work Rishi.

It was a good game to play and all of the requirements seemed to be there. It was well organised and commented.

I would suggest that next time you ensure to not use Magic Numbers/Characters.

Also you had a method at the bottom that you never used so I am unsure why it was there.

K 10 / 10
I  15 / 15
C 10 / 10
A 9 / 10

97.7%
